[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_fusion = "STF3iH1vGcBEmqc7bqFmyq2cHbJq6vaQrD6EkKuH22M"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ"

[[test.validator.clone]]
address = "CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR"

[[test.validator.clone]]
address = "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"

[[test.validator.clone]]
address = "Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g"

[[test.validator.clone]]
address = "gatem74V238djXdzWnJf94Wo1DcnuGkfijbf3AuBhfs"

[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

[[test.validator.clone]]
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
