[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_fusion = "STFyNpLRuUnxko7TPNqNR1g1EapVj4AnXkAFy2TGbj3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# MPL Core
[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
# Token Metadata
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
# Token Auth Rules
[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"
# MPL System Extras
[[test.validator.clone]]
address = "SysExL2WDyJi9aRZrXorrjHJut3JwHQ7R9bTyctbNNG"
# MPL Token Extras
[[test.validator.clone]]
address = "TokExjvjJmhKaRBShsBAsbSvEWMA1AgUNK7ps4SAc2p"
# SPL Token 2022
[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
# Metaplex Default RuleSet
[[test.validator.clone]]
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"